# Generated by Django 3.0 on 2019-12-16 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pathology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_usecase_occurences',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 16, 17, 9, 59, 238463)),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 16, 17, 9, 59, 237465)),
        ),
    ]
